#page title
page_title                                :

# App Info
ios_app_id                                : 6446344230
appstore_link                             :
playstore_link                            :
presskit_download_link                    :

app_icon                                  : assets/icon.png
app_name                                  : MyGPT – OpenAI API Chatbot
app_price                                 :
app_description                           : Get ChatGPT Plus for a fraction of the price

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Alex Plekhanov                              
your_link                                 : https://aplekhanov.com
your_city                                 :                                 
email_address                             : mail@aplekhanov.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : aplekhanov
youtube_username                          :

# Feature List 
features                                  :

  - title                                 : Speedy API Responses
    description                           : Enjoy fast and accurate responses powered by the API
    fontawesome_icon_name                 : bolt

  - title                                 : One-Tap Copy
    description                           : Effortlessly copy message text with a single tap
    fontawesome_icon_name                 : clone
      
  - title                                 : Instant Reset
    description                           : Reset the chat instantly for a fresh start whenever needed
    fontawesome_icon_name                 : sync


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg
cover_overlay_color                       : "#1da37f"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
